#!/bin/sh
# https://wiki.archlinux.org/index.php/Laptop#hibernate_on_low_battery_level

acpi -b | awk -F'[,:%]' '{print $2, $3}' | {
	read -r status capacity

	if [ "$status" = Discharging -a "$capacity" -lt 20 ]; then
		logger "Critical battery threshold"
		systemctl suspend
	fi
}
