#!/usr/bin/env sh
cnf () {
    echo "Usage: ./media play, ./media stop, ./media prev, ./media next"
}

if pgrep cmus > /dev/null; then
    case "$1" in
	"play") cmus-remote -u;;
	"stop") cmus-remote -s;;
	"next") cmus-remote -n;;
	"prev") cmus-remote -r;;
	*)      cnf;;
    esac
elif pgrep mpd > /dev/null; then
    case "$1" in
	"play")               mpc toggle;;
	"stop"|"next"|"prev") mpc $1;;
	*)                    cnf;;
    esac
elif pgrep spotify > /dev/null; then
    case "$1" in
	"play")        playerctl play-pause;;
	"prev")        playerctl previous;;
	"stop"|"next") playerctl $1;;
	*)             cnf;;
    esac
else
    echo "No music player is currently running!"
fi

# vim:ft=sh
