#!/usr/bin/env sh
rofi \
    -show run \
    -fuzzy \
    -lines 3 \
    -eh 1 \
    -width 500 \
    -padding 80 \
    -opacity 90 \
    -bw 0 \
    -color-enabled \
    -color-window "#E62B303B" \
    -color-normal "#002B303B","#C0C5CE","#002B303B","#002B303B","#8FA1B3" \
    -font "Source Sans Pro 18"
