#!/usr/bin/env sh
rofi \
    -show run \
    -fuzzy \
    -lines 3 \
    -eh 1 \
    -width 30 \
    -padding 60 \
    -opacity 90 \
    -bw 0 \
    -color-enabled \
    -color-window "#E6343D46" \
    -color-normal "#00343D46","#DFE1E8","#00343D46","#00343D46","#96b5b4" \
    -font "Source Sans Pro 18"
