#!/usr/bin/env sh

echo "
1) Openbox
2) i3

0) exit
"

read -p "Please choose a window manager " input
case $input in
    1) startx /usr/bin/openbox-session;;
    2) startx /usr/bin/i3;;
    0) return;;
    *) echo "Invalid input";;
esac
