#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &
~/scripts/startup &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width  2
bspc config window_gap   10

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a feh state=floating
bspc rule -a Thunar state=floating
bspc rule -a File-roller state=floating
bspc rule -a Firefox desktop='^1'
